language: cpp
sudo: enabled
services:
- docker
stages:
- test
jobs:
  include:
    stage: test
    install:
      - sudo docker pull slocomptech/docker-arduino:latest
      - sudo docker run -it -d --name buildenv slocomptech/docker-arduino bash
      - sudo docker ps
    before_script:
      - sudo docker exec buildenv "git clone https://github.com/SloCompTech/QList QList"
    script:
      - sudo docker exec buildenv "arduino-builder -hardware \${ARDUINO_HARDWARE} -tools \${ARDUINO_TOOLS}/avr \${ARDUINO_TOOLS_BUILDER} -libraries \${ARDUINO_LIBS} ./QList -fqbn \${A_FQBN}:uno QList/examples/SimpleList/SimpleList.ino"
    after_script:
      - rm -rf *
      - sudo docker exec buildenv "exit"
      - sudo docker ps -a