language: cpp
sudo: enabled
env:
- DOCKER_COMMAND="sudo docker"
services:
- docker
stages:
- test
jobs:
  include:
    stage: test
    install:
      - ${DOCKER_COMMAND} pull slocomptech/docker-arduino:latest
      - ${DOCKER_COMMAND} run -it -d --name buildenv slocomptech/docker-arduino bash
      - ${DOCKER_COMMAND} ps
    before_script:
      - ${DOCKER_COMMAND} exec buildenv "git clone https://github.com/SloCompTech/QList QList"
    script:
      - ${DOCKER_COMMAND} exec buildenv "arduino-builder -hardware ${ARDUINO_HARDWARE} -tools ${ARDUINO_TOOLS}/avr ${ARDUINO_TOOLS_BUILDER} -libraries ${ARDUINO_LIBS} ./QList -fqbn ${A_FQBN}:uno Qlist/examples/SimpleList/SimpleList.ino"
    after_script:
      - rm -rf *
      - ${DOCKER_COMMAND} exec buildenv "exit"
      - ${DOCKER_COMMAND} ps -a