language: cpp
sudo: enabled
services:
- docker
stages:
- test
jobs:
  include:
    stage: test
    install:
      - sudo docker pull slocomptech/docker-arduino:latest
      - sudo docker run -it -d --name buildenv slocomptech/docker-arduino bash
      - sudo docker ps
    before_script:
      - sudo docker exec buildenv git clone https://github.com/SloCompTech/QList QList
      - sudo docker exec buildenv echo "arduino:avr:uno" >> arduino_platforms.txt && \
        echo "arduino:avr:mega" >> arduino_platforms.txt && \
        echo "arduino:avr:nano" >> arduino_platforms.txt && \
        echo "arduino:avr:mini" >> arduino_platforms.txt && \
        echo "arduino:avr:micro" >> arduino_platforms.txt
    script:
      - sudo docker exec buildenv bash -c 'arduino_build_lib QList'
    after_script:
      - sudo docker stop buildenv
      - sudo docker rm buildenv
      - sudo docker rmi slocomptech/docker-arduino:latest
      - sudo docker ps -a